---
kind: pipeline
name: drone-autoscaler
type: docker

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: default
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - go get
  - go test -v -cover ./...

- name: test_postgres
  pull: default
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - cd store
  - go test -v
  environment:
    DATABASE_CONFIG: host=postgres user=postgres password=password dbname=test sslmode=disable
    DATABASE_DRIVER: postgres

- name: test_mysql
  pull: default
  image: golang
  volumes:
  - name: deps
    path: /go
  commands:
  - cd store
  - go test -v
  environment:
    DATABASE_CONFIG: "root:password@tcp(mysql:3306)/test?parseTime=true"
    DATABASE_DRIVER: mysql


- name: build
  image: plugins/gcr
  settings:
    cache_from: eu.gcr.io/antha-images/drone-autoscaler:latest
    context: ./
    dockerfile: ./Dockerfile
    json_key:
      from_secret: google_credentials
    registry: eu.gcr.io
    repo: eu.gcr.io/antha-images/drone-autoscaler
    tags:
    - latest


volumes:
- name: deps
  temp: {}

services:
- name: postgres
  pull: default
  image: postgres:9
  environment:
    POSTGRES_DB: test
    POSTGRES_PASSWORD: password

- name: mysql
  pull: default
  image: mysql:5
  environment:
    MYSQL_DATABASE: test
    MYSQL_ROOT_PASSWORD: password


trigger:
  event:
    - push # only deploy when building branches, not tags
  branch:
    - master
    - gcp-spot-vms

...

